# Hello, Piazza!

In this section we will describe each of the major Piazza features. We will provide a text description of the what the feature does and an example of how to use the feature's REST API.


## Setup

Prior to using the API, you need to have an API key and some environment variables set properly.


### Setting `$PZSERVER`

The `PZSERVER` environment variable needs to be set to the name of the API Gateway of your Piazza instance. Typically this will look something like:

    export PZSERVER=pz-gateway.venicegeo.io


### Generating Your API Key

For secure access to Piazza, each HTTP request must include an API key generated for your account. Assuming you have already set `$PZSERVER` in the previous section, you can now generate a key from the command line: 

    curl -u USERNAME:PASSWORD https://$PZSERVER/key

where USERNAME and PASSWORD are your actual username and password. (You may need to put double-quotes around the password if it contains "special" characters.)

The JSON response you get back will look similar to this:

    {
        "type" : "uuid",
        "uuid" : "45a1ba5d-cd7b-4c83-bd81-2fa2a03817d4"
    }


### Setting `$PZKEY`

You can now set the `$PZKEY` environment variable to your new key, the `uuid` value:

    export PZKEY=45a1ba5d-cd7b-4c83-bd81-2fa2a03817d4

As a convenience, if `$PZKEY` is not set, the example scripts look in the file `~/.pzkey` for the key for your server. The `.pzkey` file contains just a JSON map from server names to keys:

    {
        "pz-gateway.venicegeo.io": "45a1ba5d-cd7b-4c83-bd81-2fa2a03817d4",
        "pz-gateway.piazza4all.com": "2525ad6a-aae9-41f0-9caf-c21b8fa4d7d2"
    }

If you have `$PZSERVER` set to `pz-gateway.venicegeo.io`, the scripts will set `$PZKEY` to the correct key to use for that machine.


## Some Notes About the Examples

The code examples in this guide are presented as shell scripts that use `curl` to make the HTTP calls and JSON for the request and response payloads. To simplify the examples, the scripts rely on a setup script, helpfully named link:scripts/setup.sh[setup.sh], which will verify you have `$PZSERVER` and `$PZKEY` (or `~/.pzkey`) set correctly. It will also define some helpful aliases and functions to make the examples shorter, such as pre-setting some required optiuons for`curl`.

Some of the example scripts require one or more input arguments. These are expected to be provided on the command-line as simple strings. The scripts will verify the right number of arguments was provided.

The example scripts generally produce output. In most cases, the output will be a JSON object to `stdout`.

As an extra aid for both learning and testing, the script link:scripts/runall.sh[runall.sh] is provided. This script runs each of the example scripts in order, passing the outputs from one to the inputs of the next, and verifying those outputs are correct. (To use `runall.sh` you must have the wonderfull tool link:https://stedolan.github.io/jq/[jq] installed.)


## Hello!

With the setup work completed, we will now begin with a simple "health check" ping to the API Gateway to verify that we have a functioning instance of Piazza to talk to.

link:scripts/3-hello.sh[3-hello.sh]
[source,bash]
----
include::scripts/3-hello.sh[]
----

Note the line invoking `setup.sh`, as mentioned above, and other nonessential lines. In subsequent listings in this document, we will omit those sorts of lines and only show the "important" commands. (The full script is always available by following the link, however.)

You can run this script simply as:

    $ ./3-hello.sh

and it should return a message similar to this:

    Hello, Health Check here for pz-gateway.

NOTE: You should verify that the health check script works correctly before continuing with this tutorial. If it does not work, make sure you have the right server name, a valid API key,and correctly set `$PZSEVER` and `$PZKEY` environment variables.


## Other Helpful Tools

As you work through this tutorial, you might find these two additional Piazza resources helpful:

* `pz-swagger` is a browser-based UI for exploring Piazza's REST API. It is located at the same parent address as your `pz-gateway` host, e.g. `pz-swagger.venicegeo.io`. If you are not familiar with Swagger, see http://swagger.io[swagger.io].

* `pz-sak` is a developer-level tool for directly interacting with some of Piazza's public and private services: for example, you can use SAK to examine log files, check the status of jobs, and perform metadata queries. It can be also be found under the same parent host address, e.g. `pz-sak.venicegeo.io`. _SAK is a tool for debugging and testing only; it is not to be used in production. Contact the Piazza team for assistance with SAK._
