# Hello, Piazza!

We now describe each of the major Piazza features. We will provide a text description of the what the feature does and an example of how to use the feature's REST API via the Gateway.

The code examples are presented as extracts of shell scripts using `curl` to make the HTTP calls, JSON for the payloads and returned objects, and in some cases other shell magic to extract resource ids or validate the results. Because they are just extracts of scripts, however, they may not work with a simple copy-paste: in most cases this because `$PZDOMAIN` needs to be set to point to your instance of Piazza, as well as the `$PZKEY` and `$PZPASS` environment variables.footnote:[This will be handled more cleanly in a future release] You can find the complete scripts in Piazza's `pz-docs` repository. Those scripts are regularly tested against the current Piazza build, so they should work as advertised: if they do not, please contact the Piazza team.

You can use the link:scripts/setup.sh[setup.sh] script to generate an API key using your credentials. Run the script, passing it your `PZDOMAIN`, `PZUSER` and `PZPASS` credentials and it will create a `.pzenv` file with a new API key. You can then

    source .pzenv

from the command line or move the file to your home directory

    mv .pzenv ~/

and add

    source ~/.pzenv

to your `~/.bash_env` or `~/.zshenv` file in order to source it each time you log in.

NOTE: the `PZDOMAIN`, `PZKEY` and `PZPASS` environment variables are critical for many of the following scripts to work, please ensure they are set before continuing!

We will begin with a simple "health check" ping to the Gateway to verify that we have a functioning instance of Piazza to talk to.

    $ ./3-hello-full.sh

link:scripts/3-hello-full.sh[3-hello-full.sh]
[source,bash]
----
include::scripts/3-hello-full.sh[]
----

In the examples that follow, we will only show the portions of the script that are relevant, typically omitting the setup and teardown code. The above script might be shown as just this:

link:scripts/3-hello.sh[3-hello.sh]
[source,bash]
----
include::scripts/3-hello.sh[tags=public]
----

NOTE: You should verify that the health check script works before continuing with this tutorial.

As you work through this tutorial, you might find these two additional Piazza resources helpful:

* `pz-swagger.$DOMAIN` is a browser-based UI for exploring Piazza's REST API. If you are not familiar with Swagger, see http://swagger.io[swagger.io].

* `pz-sak.$DOMAIN` is a developer-level tool for directly interacting with some of Piazza's public and private services: for example, you can use SAK to examine log files, check the status of jobs, and perform metadata queries. SAK is an internal tool for debugging and testing only; it is not to be used in production. Contact the Piazza team for assistance with SAK.
