# Workflow Service

Piazza provides the ability for users to define and send _events_, representing some "thing" that has happened. These events can be issued either from within Piazza or by an external client. Piazza also allows for users to define _triggers_, containing both an event-condition and an action: when the condition is met, the action is performed. Taken together, _eventtypes_, _events_, and _triggers_ can be used to define _workflows_. A script that sets up the workflow described in this section can be found link:scripts/7-example.sh[here].

NOTE: By design, events and triggers are fairly primitive, low-level constructs. As Piazza matures, richer support for defining workflows may be added.

## The EventType

The user (or some service) first defines an _EventType_ which is the "schema" for the events that the user will be generating. The _EventType_ object is POSTed to `/eventType` and contains contains a _name_ (string) and a map describing the event type's parameters. It also contains a system-generated ID. For example:

[source,json]
----
{
    "name": "testevent-1468849135",
    "mapping": {
        "filename": "string",
        "code":     "string",
        "severity": "integer"
    }
}
----

The `name` must be unique across all event types in the system.

The available data types are `string`, `boolean`, `integer`, `double`, `date`, `float`, `byte`, `short`, and `long`. (By no coincidence, these are the basic types that Elasticsearch supports.)

The following script shows an example of registering an EventType. Run it using:

[source,bash]
$ ./7-eventtype.sh

[source,bash]
.link:scripts/7-eventtype.sh[7-eventtype.sh]
----
include::scripts/7-eventtype.sh[tags=public]
----


## The Trigger

The user then defines a _Trigger_ which defines what action is to be taken when a specific event occurs. The _Trigger_ is POSTed to `/trigger` and contains two parts, the _Condition_ and the _Job_. The _Condition_ defines what type of event is to be watched for and what the specific parameters of that event should be, expressed using Elasticsearch DSL query syntax against the parameters in the event type. The _Job_ defines what action is to be taken, expressed as using Gateway/Dispatcher-style syntax. The _Trigger_ also contains a system-generated ID. For example:

[source,json]
----
{
    "title": "High Severity",
    "enabled": true,
    "condition": {
        "eventTypeIds": ["98fc25e8-bd97-4444-a972-c06aa0f0edf1"],
        "query": {
            "query": {
                "bool": {
                    "must": [
                        { "match": {"severity": 5} },
                        { "match": {"code": "PHONE"} }
                    ]
                }
            }
        }
    },
    "job": {
        "createdBy": "test",
        "jobType": {
            "type": "execute-service",
            "data": {
                "serviceId": "a2898bcb-2646-4ffd-9da7-2308cb7e77d7"
            }
        }
    }
}
----

For details on constructing valid Elasticsearch DSL queries, see the <<Elasticsearch Query Syntax>> section.

In this example, the job will be executed only when our "test" event occurs with the `severity` equal to `5` and the `code` equal to `"PHONE"`.

`enabled` is a boolean value indicating whether the trigger should be "active" or not.

NOTE: the "type" field of the "condition" will likely be removed in the future, as the query DSL allows us to specify the event type directly within it; this would open up the possibility of having a condition based on multiple events.

Pass the following script an EventType ID, and it will create a generic Trigger for the given EventType:

[source,bash]
$ ./7-trigger.sh {{eventtype_id}}

[source,bash]
.link:scripts/7-trigger.sh[7-trigger.sh]
----
include::scripts/7-trigger.sh[tags=public]
----


## The Event

The user may generate an _Event_ of that _EventType_ to indicate some interesting condition has occurred. The _Event_ object is POSTed to `/event` and contains the ID of the _EventType_, the date the event occurred, and the parameters of the event. It also contains a system-generated ID. For example:

[source,json]
----
{
    "eventTypeId": "98fc25e8-bd97-4444-a972-c06aa0f0edf1",
    "data": {
        "filename": "dataset-c",
        "severity": 5,
        "code": "PHONE"
    }
}
----

The following script POSTs an event with an EventType ID passed in by the user:

[source,bash]
$ ./7-event.sh {{eventtype_id}}

[source,bash]
.link:scripts/7-event.sh[7-event.sh]
----
include::scripts/7-event.sh[tags=public]
----


## The Alert

Whenever the condition of a _Trigger_ is met, the system will create an _Alert_ object. The user can GET a list of alerts from `/alert`. The _Alert_ object contains the ids of the _Trigger_ that was hit and the _Event_ which caused it. It also contains the now ubiquitous system-generated ID. For example:

[source,json]
----
{
  "statusCode": 200,
  "type": "alert-list",
  "data": [
    {
      "alertId": "58d1ad21-75d0-4ee4-8429-c687b9249cc5",
      "triggerId": "170619d6-8f4e-4dc4-bcb6-8b0862e0138f",
      "eventId": "baa98fc7-f282-4caf-b35d-c2050eca010c",
      "jobId": "ab62ae7e-432b-4b61-a831-4a80b6ce836e",
      "createdBy": "",
      "createdOn": "2016-07-18T13:41:28.571761514Z"
    }
  ],
  "pagination": {
    "count": 1,
    "page": 0,
    "perPage": 10,
    "sortBy": "alertId",
    "order": "asc"
  }
}
----

The following script gets the list of alerts currently in the Piazza system, with default pagination and per_page settings:

[source,bash]
$ ./7-get-alerts.sh

[source,bash]
.link:scripts/7-get-alerts.sh[7-get-alerts.sh]
----
include::scripts/7-get-alerts.sh[tags=public]
----

The query parameter `?triggerId=id` is provided to allow the list to be filtered to only the alerts of interest.
